humanoid_walking:
  ros__parameters:
    # モデル/時間
    zh: 0.80
    g: 9.81
    dt: 0.01
    Tsup: 0.80
    Tds: 0.20

    # 歩幅
    sx: 0.20
    sy: 0.20
    start_leg: "LEFT"

    # 初期支持足
    px0: 0.00
    py0: 0.10      # = sy/2

    # 初期CoM
    x0: 0.00       
    y0: 0.00
